/*
 * ZERO AI — Terms of Service Page
 */

import { Link } from "wouter";

const LOGO = "https://d2xsxph8kpxj0f.cloudfront.net/310519663342337625/biHYpnWi4gbAo4jVFbvk4g/zero-ai-logo-new_0acbc76c.webp";
const mono = "'IBM Plex Mono', monospace";
const syne = "'Syne', sans-serif";
const dm = "'DM Sans', sans-serif";

const SECTIONS = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content: `By accessing or using the Zero AI website (zeroai.vip) and any associated services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.

These terms apply to all visitors, users, and others who access or use our services, including participation in the early access waitlist program.`,
  },
  {
    id: "description",
    title: "2. Description of Service",
    content: `Zero AI is a personal AI operating system currently in development. The website provides information about the product, a waitlist for early access, and an AI chat demonstration.

The service is provided "as is" during the development phase. Features, availability, and pricing are subject to change without notice. We will make reasonable efforts to notify waitlist members of significant changes.`,
  },
  {
    id: "waitlist",
    title: "3. Waitlist Program",
    content: `By joining the Zero AI waitlist, you:

— Provide accurate and complete information about yourself
— Agree to receive email communications about Zero AI's development and launch
— Understand that joining the waitlist does not guarantee early access or any specific pricing
— May unsubscribe from communications at any time

We reserve the right to accept or decline waitlist applications at our sole discretion.`,
  },
  {
    id: "intellectual-property",
    title: "4. Intellectual Property",
    content: `All content on this website — including text, graphics, logos, icons, images, and software — is the property of Zero AI and is protected by applicable intellectual property laws.

You may not reproduce, distribute, modify, or create derivative works from any content on this website without explicit written permission from Zero AI.

The Zero AI name, logo, and brand identity are trademarks of Zero AI. Unauthorized use of our trademarks is prohibited.`,
  },
  {
    id: "user-conduct",
    title: "5. User Conduct",
    content: `When using our services, you agree not to:

— Use the service for any illegal purpose or in violation of any laws
— Attempt to gain unauthorized access to any part of our systems
— Transmit any harmful, offensive, or disruptive content
— Impersonate Zero AI or any of its representatives
— Use automated tools to scrape or extract data from our website
— Interfere with the proper functioning of the service

Violation of these terms may result in immediate termination of your access.`,
  },
  {
    id: "ai-demo",
    title: "6. AI Chat Demonstration",
    content: `The AI chat feature on our website is provided for demonstration purposes only. Responses generated by the AI are not professional advice of any kind — not legal, financial, medical, or otherwise.

The AI demonstration uses language models that may occasionally produce inaccurate or inappropriate responses. Zero AI is not responsible for any decisions made based on AI-generated content.

Do not share sensitive personal, financial, or confidential information in the AI chat demonstration.`,
  },
  {
    id: "limitation",
    title: "7. Limitation of Liability",
    content: `To the maximum extent permitted by applicable law, Zero AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, our services.

Our total liability for any claims arising from these terms or your use of our services shall not exceed the amount you have paid us in the twelve months preceding the claim (which may be zero during the free waitlist phase).`,
  },
  {
    id: "disclaimer",
    title: "8. Disclaimer of Warranties",
    content: `Our services are provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that:

— The service will be uninterrupted or error-free
— Any defects will be corrected
— The service is free of viruses or other harmful components
— The results of using the service will meet your requirements

Zero AI is in active development. Downtime, data loss, and feature changes are possible.`,
  },
  {
    id: "governing-law",
    title: "9. Governing Law",
    content: `These terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law provisions.

Any disputes arising from these terms or your use of our services shall be resolved through good-faith negotiation. If negotiation fails, disputes shall be submitted to binding arbitration.`,
  },
  {
    id: "changes",
    title: "10. Changes to Terms",
    content: `We reserve the right to modify these terms at any time. We will provide notice of significant changes by updating the date at the top of this page and, where appropriate, notifying waitlist members by email.

Your continued use of our services after changes constitutes acceptance of the updated terms.`,
  },
  {
    id: "contact",
    title: "11. Contact",
    content: `For questions about these terms, please contact us:

Email: legal@zeroai.vip
Twitter: @_zeroai

We will respond to legal inquiries within 5 business days.`,
  },
];

export default function Terms() {
  return (
    <div
      className="min-h-screen"
      style={{ background: "oklch(0.075 0.008 265)", color: "oklch(0.93 0.005 265)" }}
    >
      {/* Header */}
      <header
        className="sticky top-0 z-50 border-b"
        style={{
          background: "oklch(0.075 0.008 265 / 0.92)",
          backdropFilter: "blur(12px)",
          borderColor: "rgba(255,255,255,0.06)",
        }}
      >
        <div className="container">
          <div className="flex items-center justify-between h-14">
            <Link href="/">
              <a className="flex items-center gap-2">
                <img src={LOGO} alt="Zero AI" className="w-7 h-7 object-contain" />
                <span className="text-sm font-semibold" style={{ fontFamily: syne }}>ZERO AI</span>
              </a>
            </Link>
            <Link href="/">
              <a
                className="text-xs transition-colors"
                style={{ fontFamily: dm, color: "oklch(0.55 0.01 265)" }}
                onMouseEnter={(e) => ((e.currentTarget as HTMLAnchorElement).style.color = "oklch(0.85 0.005 265)")}
                onMouseLeave={(e) => ((e.currentTarget as HTMLAnchorElement).style.color = "oklch(0.55 0.01 265)")}
              >
                ← Back to Home
              </a>
            </Link>
          </div>
        </div>
      </header>

      <div className="container py-16">
        <div className="max-w-3xl">
          {/* Title */}
          <div className="mb-12">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-xs tracking-widest uppercase" style={{ fontFamily: mono, color: "oklch(0.76 0.18 155)" }}>
                Legal
              </span>
              <span className="flex-1 h-px" style={{ background: "oklch(0.76 0.18 155 / 0.3)" }} />
            </div>
            <h1 className="font-bold mb-3" style={{ fontFamily: syne, fontSize: "clamp(2rem, 4vw, 3rem)" }}>
              Terms of Service
            </h1>
            <p className="text-sm" style={{ fontFamily: mono, color: "oklch(0.45 0.008 265)" }}>
              Last updated: March 15, 2026
            </p>
            <p className="mt-4 text-sm leading-relaxed" style={{ fontFamily: dm, color: "oklch(0.55 0.01 265)" }}>
              Please read these Terms of Service carefully before using Zero AI's website and services. These terms govern your access to and use of our platform.
            </p>
          </div>

          {/* Sections */}
          <div className="space-y-10">
            {SECTIONS.map((section) => (
              <div key={section.id} id={section.id}>
                <h2 className="font-bold mb-4" style={{ fontFamily: syne, fontSize: "1.1rem", color: "oklch(0.88 0.005 265)" }}>
                  {section.title}
                </h2>
                <div
                  className="text-sm leading-relaxed whitespace-pre-line"
                  style={{ fontFamily: dm, color: "oklch(0.62 0.01 265)", lineHeight: 1.8 }}
                >
                  {section.content}
                </div>
                <div className="mt-6 h-px" style={{ background: "rgba(255,255,255,0.04)" }} />
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t py-8" style={{ borderColor: "rgba(255,255,255,0.06)" }}>
        <div className="container flex flex-col sm:flex-row items-center justify-between gap-4">
          <span className="text-xs" style={{ fontFamily: mono, color: "oklch(0.35 0.006 265)" }}>
            © 2026 Zero AI. All rights reserved.
          </span>
          <div className="flex items-center gap-6">
            {[{ href: "/docs", label: "Docs" }, { href: "/changelog", label: "Changelog" }, { href: "/privacy", label: "Privacy" }].map((link) => (
              <Link key={link.href} href={link.href}>
                <a
                  className="text-xs transition-colors"
                  style={{ fontFamily: mono, color: "oklch(0.45 0.008 265)" }}
                  onMouseEnter={(e) => ((e.currentTarget as HTMLAnchorElement).style.color = "oklch(0.76 0.18 155)")}
                  onMouseLeave={(e) => ((e.currentTarget as HTMLAnchorElement).style.color = "oklch(0.45 0.008 265)")}
                >
                  {link.label}
                </a>
              </Link>
            ))}
          </div>
        </div>
      </footer>
    </div>
  );
}
